import { test, after } from "node:test";
import assert from "node:assert/strict";
import os from "node:os";
import path from "node:path";
import fs from "node:fs";
process.env.NODE_ENV = "test";
const tmp = path.join(os.tmpdir(), `taptime-credentials-${process.pid}.db`);
process.env.TAPTIME_DB = tmp;
const { app } = await import("../index.js");
const { db, insert } = await import("../db.js");
const { hashPassword, createSession, verifyPassword } = await import("../auth.js");
const server = app.listen(0, "127.0.0.1");
await new Promise((resolve) => server.on("listening", resolve));
const base = `http://127.0.0.1:${server.address().port}/api`;
async function request(route, token, body, factory = false) {
  const res = await fetch(base + route, { method: body ? "PUT" : "GET", headers: { "Content-Type": "application/json", ...(factory ? { "X-Factory-Key": "dev-factory" } : { Authorization: `Bearer ${token}` }) }, body: body ? JSON.stringify(body) : undefined });
  return { status: res.status, data: await res.json() };
}
after(async () => { await new Promise((resolve) => server.close(resolve)); await db.close(); for (const suffix of ["", "-wal", "-shm"]) fs.rmSync(tmp + suffix, { force: true }); });
test("credential APIs isolate clinics, protect secrets, and update factory inventory and login", async () => {
  const now = new Date().toISOString();
  const org = await insert("INSERT INTO organizations (name, slug, created_at, updated_at) VALUES ('A', 'a', ?, ?)", now, now);
  const other = await insert("INSERT INTO organizations (name, slug, created_at, updated_at) VALUES ('B', 'b', ?, ?)", now, now);
  const mk = (o, email, role) => insert("INSERT INTO users (organization_id, first_name, last_name, email, password_hash, role) VALUES (?, 'Test', 'User', ?, ?, ?)", o, email, hashPassword("oldpass"), role);
  const admin = await mk(org, "admin@a.test", "admin");
  const outsider = await mk(other, "admin@b.test", "owner");
  const member = await mk(org, "member@a.test", "employee");
  const token = await createSession(admin), oldSession = await createSession(admin), memberToken = await createSession(member);
  const tag = await insert("INSERT INTO provisioned_tags (code, claim_code, organization_id, created_at) VALUES ('one', 'ONE', ?, ?)", org, now);
  await insert("INSERT INTO provisioned_tags (code, claim_code, created_at) VALUES ('two', 'TWO', ?)", now);
  assert.equal((await request('/admin/credentials', '')).status, 401);
  assert.equal((await request('/admin/credentials', memberToken)).status, 403);
  assert.equal((await request('/factory/tags', token)).status, 401);
  const accounts = (await request('/admin/credentials', token)).data.accounts;
  assert.equal(accounts.length, 1);
  assert.equal(accounts[0].password_set, 1);
  assert.equal(JSON.stringify(accounts).includes('password_hash'), false);
  assert.equal((await request(`/admin/credentials/${outsider}`, token, { email: 'stolen@b.test' })).status, 404);
  assert.equal((await request(`/admin/credentials/${admin}`, token, { email: 'ADMIN@B.TEST' })).status, 400);
  assert.equal((await request(`/admin/credentials/${admin}`, token, { email: 'bad' })).status, 400);
  assert.equal((await request(`/admin/credentials/${admin}`, token, { email: 'admin@a.test', password: 'short' })).status, 400);
  assert.equal((await request(`/admin/credentials/${admin}`, token, { email: 'NEW@A.TEST', password: 'newpassword' })).status, 200);
  assert.equal((await request('/admin/credentials', oldSession)).status, 401);
  assert.equal((await request('/admin/credentials', token)).status, 200);
  let user = await db.get('SELECT * FROM users WHERE id = ?', admin);
  assert.equal(user.email, 'new@a.test');
  assert.ok(verifyPassword('newpassword', user.password_hash));
  assert.equal(verifyPassword('oldpass', user.password_hash), false);
  const tags = (await request('/factory/tags', '', undefined, true)).data.tags;
  assert.equal(tags.find((t) => t.id === tag).accounts[0].email, user.email);
  assert.deepEqual(tags.find((t) => t.code === 'two').accounts, []);
  assert.equal((await request(`/factory/tags/${tag}/credentials/${outsider}`, '', { email: 'no@b.test' }, true)).status, 404);
  assert.equal((await request(`/factory/tags/${tag}/credentials/${admin}`, '', { email: 'factory@a.test', password: '' }, true)).status, 200);
  user = await db.get('SELECT * FROM users WHERE id = ?', admin);
  assert.ok(verifyPassword('newpassword', user.password_hash));
  assert.equal((await request('/admin/credentials', token)).status, 401);
  const login = async (email, password) => fetch(base + '/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) });
  assert.equal((await login('factory@a.test', 'newpassword')).status, 200);
  assert.equal((await login('factory@a.test', 'oldpass')).status, 401);
  assert.equal((await login('new@a.test', 'newpassword')).status, 401);
  const audit = JSON.stringify(await db.all("SELECT * FROM audit_log WHERE action = 'credentials_update'"));
  assert.equal(audit.includes('newpassword'), false);
  assert.equal(audit.includes(user.password_hash), false);
});
